---
title: "Preprocesamiento"
output: html_notebook
---

```{r}
install.packages("nnet")
install.packages("RWeka")
install.packages("neuralnet")
library(caret)
library(nnet)
library(RWeka)
library(neural)
library(dummy)
library(neuralnet)

```
```{r}
# Utilizar los mismos conjuntos de entrenamiento y de prueba
trainHDT8<-trainHDT4
testHDT8<-testCompleto
```
```{r}
# Matriz de tuneo
tuneGrid <- expand.grid(size = c(5, 15), decay = c(1, 0.1, 0.01, 0.001, 10))

# Parametros de control
ctrl <- trainControl(method = "cv",  # cross validation
                     number = 100, # Numero de iteraciones     
                    #  verboseIter = TRUE # Impresiones
                     ) 

# Train the model with tuning
modeloCaret <- train(Category ~ ., 
                     data = trainHDT8, 
                     method = "nnet", 
                     trControl = ctrl, 
                     tuneGrid = tuneGrid,
                     trace = FALSE)

# Make predictions on the test set
testHDT8$prediccionCaret <- predict(modeloCaret, newdata = testHDT8[,1:38])

# Calculate confusion matrix
cfmCaret <- confusionMatrix(testHDT8$prediccionCaret, testHDT8$Category)
cfmCaret

```